[package]
name = "matchmaker"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
csv = "1.3.1"
rand = "0.9.1"
serde = {version = "1.0.219", features=["derive"]}
tokio = { version = "1.45.0", features = ["full"] }
